### ISSUE TITLE
webpack build

### ISSUE THREAD

**Issue by igor-slotin** [fixate/angular-social-links#22]
missed a comma in file angular-social-links.js in 5 row
handler: '&customHandler'

**Comment by larrybotha** [comment]
That comma is optional in both JS and CoffeeScript, especially since it's the last (and only) property in that literal.

Your bundled file shouldn't have any errors, wether there's a comma or not. Does your build fail? If so, what is the error?

**Comment by obuckley-kenzan** [comment]
I am getting this error when using gulp-uglify.  I added logging and this was the output
```
{ [Error: bower_components/vendor.min.js: Unexpected token name «socialWidth», expected punc «,»]
  message: 'bower_components/vendor.min.js: Unexpected token name «socialWidth», expected punc «,»',
  fileName: 'bower_components/vendor.min.js',
  lineNumber: 54486,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1525:18)\n    at js_error (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1533:11)\n    at croak (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2024:9)\n    at token_error (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2032:9)\n    at expect_token (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2045:9)\n    at expect (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2048:36)\n    at eval (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2574:44)\n    at eval (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2071:24)\n    at expr_atom (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2531:35)\n    at maybe_unary (eval at <anonymous> (/Users/obuckley/Workspace/thomson-reuters/repo/ips/1p-frontend-new/1p-frontend-webapp/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2707:19)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
```

`socialWidth` is the next line after the missing comma

```
  sharedScopeDefinition = {
    handler: '&customHandler'
    socialWidth: '@',
    socialHeight: '@'
  };
```

**Comment by yjwong** [comment]
I'm also facing this issue using grunt-contrib-uglify. Same cause, the missing comma.

**Comment by larrybotha** [comment]
ye, we must have merged a commit that was made against the compiled file directly, and not against the coffee and then compiled. That merge into the js file contained the syntax error, while the coffee file still had only one property.

Both the coffee file and the compiled file have been updated - please pull and let me know if you come across any errors.
